### ISSUE TITLE
What is the supported python version?

### ISSUE THREAD

**Issue by six6egrees** [TomographyLab/NiftyRec#1]
Trying to install the python package following the instructions. I'm using python 3.7 on Windows. When running setup.py in the NiftyRec/niftyrec/python directory the following error occurs:

`File "setup.py", line 6
    print "Python wrapper version: ",VERSION
                                   ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Python wrapper version: ",VERSION)?`

This looks like the python 2.x print function (lack of parentheses). Does this mean that only python 2 is supported? I could not find any information regarding python or other package version dependencies on the website or here.

**Comment by mscipio** [comment]
Hi! Yes, for what concernes the repository of NiftyRec and Occiput, only python 2.7 is supported.
However, the porting of the library to python 3.x has begun and it is called ['tomolab'](https://github.com/TomographyLab/TomoLab).
If you refer to the Docker image you can download [here](https://github.com/TomographyLab/DockerImage) you will find everything already installed and ready to use, with no need to compile anything.

Let me know if this help.

**Comment by six6egrees** [comment]
Sorry, I forgot to close this issue. Thank you for your fast response.
